sudo: false
language: node_js
node_js:
- 7.7.1
notifications:
  disabled: true
deploy:
  provider: heroku
  api_key:
    secure: ecsCPD9UqGwgvFvnfzmgLjMsouGT8Twt+YfgQ95FEZRiAg0448e98ncUhZCt/0oAr1YBZEh2FEwKWvducX9iXSQGq0pOQdCK3V96Ols5stRED5r7A1zlFTatunRw3IDFnVsvXK/MQyqyczo+nLscZuIS7sdq/w0nN7BvFUbrIoq5KmqYn2HprI3z6SXqidH+VtRRiSNLxsO94jwWc7teUz9YFzHQE1IQIxYgqN0y8f1Ru5PdQ4tz5iqdYHolKNJLervY2XfpY547Y+fpgGmlH3aI8ACwgMkixEGuDFfGlfe6PLqemdjPN/wwt+CiymoxlTHOzqLqxg5UYtRjQgeNOm7thgaLXkaBBR9YgSPqsdedhpuAJVk5JLlS63rECo4R/scqEUz6GFWG7KThN6bNDUDK+SrbPfPpGltLMhXzA569S1Lkiofwx/y3GhtMDBrR1WUp1CltkD9Ae3N9sICKtlTNbL2oRexm/Yk5c36VIouw2cMURa6ON4JJjRNAQ/kH+eEeh8NFqRIpUtrZyHhDBL6F0DVgFnTyLJyDNGj/9DfKKbf+TjFSOf/iLQUYXxU2kEoH1B4TRtsGvMP1WL2HN9BHrwT6aPJ5VqgGDLlBeXyMJVPNiGXsmWv6O+8SCF0/mpVYVY3yvFTyMrSxGZW1TlNyOKUkr0N3AMLBze5AQpM=
  app: vast-stream-78160
  on:
    repo: erickzhao/badge
